# Generated by Django 2.2.2 on 2020-04-29 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, null=True)),
                ('image', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Add_Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carname', models.CharField(max_length=100, null=True)),
                ('fixedcarimg', models.FileField(null=True, upload_to='')),
                ('img1', models.FileField(null=True, upload_to='')),
                ('img2', models.FileField(null=True, upload_to='')),
                ('img3', models.FileField(null=True, upload_to='')),
                ('img4', models.FileField(null=True, upload_to='')),
                ('cartype', models.CharField(max_length=100, null=True)),
                ('bodycover', models.CharField(max_length=100, null=True)),
                ('carmodel', models.CharField(max_length=100, null=True)),
                ('bodytype', models.CharField(max_length=100, null=True)),
                ('carcompany', models.CharField(max_length=100, null=True)),
                ('carprice', models.CharField(max_length=100, null=True)),
                ('carnumber', models.CharField(max_length=100, null=True)),
                ('carlength', models.IntegerField(null=True)),
                ('carwidth', models.IntegerField(null=True)),
                ('carheight', models.IntegerField(null=True)),
                ('seatingcapacity', models.IntegerField(null=True)),
                ('fueltype', models.CharField(max_length=100, null=True)),
                ('displacement', models.CharField(max_length=100, null=True)),
                ('maxpower', models.CharField(max_length=100, null=True)),
                ('maxtorque', models.CharField(max_length=100, null=True)),
                ('milage', models.CharField(max_length=100, null=True)),
                ('transmissiontype', models.CharField(max_length=100, null=True)),
                ('noofgear', models.CharField(max_length=100, null=True)),
                ('aircondition', models.CharField(max_length=100, null=True)),
                ('carpowerwindow', models.CharField(max_length=100, null=True)),
                ('carcenterlocking', models.CharField(max_length=100, null=True)),
                ('carabs', models.CharField(max_length=100, null=True)),
                ('airbags', models.CharField(max_length=100, null=True)),
                ('frontype', models.CharField(max_length=100, null=True)),
                ('reartype', models.CharField(max_length=100, null=True)),
                ('cardescription', models.CharField(max_length=100, null=True)),
                ('fuelcapacity', models.CharField(max_length=100, null=True)),
                ('bootspace', models.CharField(max_length=100, null=True)),
                ('foglamps', models.CharField(max_length=100, null=True)),
                ('enginedisplay', models.CharField(max_length=100, null=True)),
                ('centrallocking', models.CharField(max_length=100, null=True)),
                ('lastupdationdate', models.CharField(max_length=100, null=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car.Categary')),
            ],
        ),
    ]
