# Generated by Django 2.2.2 on 2020-04-29 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_car',
            name='carcompany',
        ),
    ]
