# Generated by Django 2.2.2 on 2020-04-29 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_remove_add_car_carcompany'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_car',
            name='fixedcarimg',
        ),
    ]
