# Generated by Django 2.2.6 on 2020-05-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='enquery',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
